k3d_ver: v5.4.6
k3d_platform: linux-amd64
k3d_mirror: https://github.com/rancher/k3d/releases/download
k3d_checksum: sha256:8075d40c74c97d2642f15f535cb48d6d6e82df143f528833a193d87caac6a176
k3d_install_dir: /usr/local/bin
k3d_url: '{{ k3d_mirror }}/{{ k3d_ver }}/k3d-{{ k3d_platform }}'
k3d_exe: '{{ k3d_install_dir }}/k3d'

kubectl_version: v1.25.3
kubectl_url: 'https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl'
kubectl_checksum: 'sha256:f57e568495c377407485d3eadc27cda25310694ef4ffc480eeea81dea2b60624'
kubectl_exe: '{{ k3d_install_dir }}/kubectl'

registry_port: 5000
registry_host: localhost

cluster_name: stuart
k3d_additional_arguments: "--volume /var/tmp/mysqld:/var/tmp/mysqld@server:0"
